# IMPORT LIBRARY

In [2]:
import cv2
import numpy as np

In [3]:
citra = cv2.imread("orange.jpg")
cv2.imshow("Citra asli", citra)
cv2.waitKey(5)
cv2.destroyAllWindows()
print(citra.shape)
print(citra.dtype)

(544, 960, 3)
uint8


In [12]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]
panjang = len(citra)
lebar = len(citra[0])
citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989*r[i,j] + 0.587*g[i,j] + 0.1141*b[i,j]

citra_gray = citra_gray.astype(np.uint8)
cv2.imshow("Abu", citra_gray)
cv2.waitKey(5)
cv2.destroyAllWindows()
print(citra_gray)

[[ 22  22  21 ...  17  22  21]
 [ 20  22  21 ...  16  20  20]
 [ 21  22  23 ...  16  19  21]
 ...
 [ 48  46  44 ... 188 186 176]
 [ 46  44  42 ... 186 189 193]
 [ 49  46  43 ... 180 189 184]]
